name: Fetch Image Links

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download PNG image links
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vR7OIutQwIUga6KhlDCx1psTnrRkKEDfeFOap_rxES0YEo2RQqbzYOLKQEah8IjEHNjvi7oyMl1qtwQ/pub?output=csv" -o amend2_image_links_png.csv

      - name: Download JPEG image links
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vS9oIgmf14CBiEZfCD4KjmWxzXjZJzvwvQvb1Jd2Ot4uwkV_-gt-Iv-IJ_ZGzxucGAkpcI0RtG7FsT1/pub?output=csv" -o amend2_image_links_jpeg.csv

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase
          git add amend2_image_links_png.csv amend2_image_links_jpeg.csv
          git diff --staged --quiet || git commit -m "Update PNG and JPEG image links"
          git push
